### ISSUE TITLE
Релиз для 7.6

### ISSUE THREAD

**Issue by aaerofeev** [papahigh/elasticsearch-keyboard-layout#1]
Добрый день, планируете ли релиз для последней версии 7.6 эластика. Хотелось бы попробовать ваш плагин. Спасибо

**Comment by npapakha** [comment]
@aaerofeev добрый! Сделаю, выложу ссылку. Спасибо за интерес к проекту

**Comment by aaerofeev** [comment]
https://github.com/papahigh/elasticsearch-keyboard-layout/pull/2
Создал пулл-реквест
