### ISSUE TITLE
если на поле, suggestion повесить icu_transform анализатор, то, индексация для кийбоарда не отработает

### ISSUE THREAD

**Issue by AlinaLoz** [papahigh/elasticsearch-keyboard-layout#5]
если на поле, suggestion повесить icu_transform анализатор, то, индексация для кийбоарда не отработает
может сможете подсказать как это обойти можно?

_Originally posted by @AlinaLoz in https://github.com/papahigh/elasticsearch-keyboard-layout/issues/3#issuecomment-856802476_

**Comment by npapakha** [comment]
привет, пожалуйста, приложи шаги для воспроизведения

**Comment by AlinaLoz** [comment]
привет, 
[example-icu-transform.zip](https://github.com/papahigh/elasticsearch-keyboard-layout/files/6622664/example-icu-transform.zip)

**Comment by npapakha** [comment]
это не ошибка плагина - так работает эластиксерч
возможным решением для тебя может быть multi field поле title с разным анализом: `title.standard` и `title.latin`
при поисковом запросе в теле suggest указывай оба саджеста на соответствующие поля
в ответе придется смотреть в оба саджеста и выбирать что стоит показать пользователю

**Comment by npapakha** [comment]
снаружи поле title останется тем же самым (при индексации/в результатах поиска)
а два независимых анализа по этому полю должны решить твою проблему саджестов

**Comment by AlinaLoz** [comment]
изивни, но не понимаю, как анализаторы могут быть независыми в этом случае, если.
эластик индексирует все, что есть в базе.
в базе лежит  **fructis**, для него неверная раскладка **акгсешы**.
latin анализатор, посмторит что в базе лежит fructis, проиндексирует как фруктис.
в моем случае, мне нужно чтобы отработало
ahernbc(слово фруктис на неверное раскладке, оно не проиндексировано keyboard, так как этого не было в базе)
 => фруктис => fructis

**Comment by npapakha** [comment]
смотри в доки про [multi fields](https://www.elastic.co/guide/en/elasticsearch/reference/current/multi-fields.html), [term vector](https://www.elastic.co/guide/en/elasticsearch/reference/current/term-vector.html), например.


смотри, ниже сниппет маппинга, обрати внимание насвойство `mappings.properties.group` - видишь у него в fields можно определять сколько угодно много анализа для одного единственного поля в json, (важный момент кстати "term_vector": "yes" в таких виртуальных филдах). при индексации ты кидаешь обыкновенный json где group - это строка, в результатах поиска ты будешь видеть тоже самое. А в поисковых запросах ты можешь ссылаться на qualified имя нужного анализа для  твоего поля те `group.keyword`, `group.stemmed` и тп

```
  "mappings": {
    "dynamic": "strict",
    "properties": {
      "keywords": {
        "type": "text",
        "analyzer": "keyword_analyzer"
      },
      "suggest": {
        "type": "completion"
      },
      "group": {
        "type": "text",
        "copy_to": "keywords",
        "analyzer": "standard_analyzer",
        "fields": {
          "keyword": {
            "type": "keyword"
          },
          "stemmed": {
            "type": "text",
            "analyzer": "stemmed_analyzer",
            "term_vector": "yes"
          },
          "ngram_default": {
            "type": "text",
            "analyzer": "ngram_default",
            "search_analyzer": "standard_analyzer",
            "term_vector": "yes"
          }
        }
      }
    }
  }
```
